name: DEV

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name imtahan

      - name: Build and push
        run: |
          docker buildx build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} --platform linux/amd64 -t imtahan.azurecr.io/frontend:${{ github.sha }} --push .

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Deploy
        run: |
          az aks get-credentials --resource-group imtahan --name imtahan --overwrite-existing
          kubectl set image deployment/frontend frontend=imtahan.azurecr.io/frontend:${{ github.sha }}
